development:
  adapter: mysql
  database: acctsoft_development
  username: acctsoftdev
  password:
  host: localhost
  port: 3306
  
test:
  adapter: mysql
  database: acctsoft_test
  username: acctsoftdev
  password:
  host: localhost
  port: 3306

production:
  adapter: mysql
  database: acctsoft_production
  username: acctsoft
  password: 
  host: localhost
  port: 3306
